### ISSUE TITLE
Probably use math_expressions instead of expressions

### ISSUE THREAD

**Issue by absar** [zuvola/flutter_simple_calculator#17]
[math_expressions](https://pub.dev/packages/math_expressions) has only vector_math as dependency, it is very well maintained, tested, and has a bigger community, which seems to be a better alternative to expressions

**Comment by JekaNS** [comment]
Looks like it should be pretty easy ))
PR: https://github.com/zuvola/flutter_simple_calculator/pull/20

**Comment by zuvola** [comment]
Merged.
Thanks!
