### ISSUE TITLE
New Versión?

### ISSUE THREAD

**Issue by lmta1** [zuvola/flutter_simple_calculator#2]
Hi¡, after updating Flutter to stable version 2.0, it tells me that sdk which depends on intl 0.17.0, intl 0.17.0 is required. Your package requires intl ^ 0.16.1 and it doesn't work with intl 0.17.0. Are you planning to update it soon? or do we have to stop using your package with flutter version 2.0? Thank you.

**Comment by zuvola** [comment]
I have released a new version.
Please use 'v2.0.0-nullsafety'.

https://pub.dev/packages/flutter_simple_calculator/versions/2.0.0-nullsafety.0

**Comment by lmta1** [comment]
Thank!!
